modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/PanSzelescik/coolgadgets/issues"
displayURL="https://minecraft.curseforge.com/projects/coolgadgets"
logoFile="logo.png"
authors="PanSzelescik"
[[mods]]
modId="coolgadgets"
version="${file.jarVersion}"
displayName="Cool Gadgets"
updateJSONURL="https://raw.githubusercontent.com/PanSzelescik/coolgadgets/master/update.json"
description='''
This mod adds a few gadgets
'''
[[dependencies.coolgadgets]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.coolgadgets]]
    modId="morelibs"
    mandatory=true
    versionRange="[2.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.coolgadgets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"